module.exports = {
    CHANGE_POST: 'CHANGE_POST',
    CHANGE_REPLY: 'CHANGE_REPLY',
    CLEAR_COMMENTS: 'CLEAR_COMMENTS',
    CREATE_THREAD: 'CREATE_THREAD',
    GET_COMMENTS: 'GET_COMMENTS',
    GET_THREADS: 'GET_THREADS'
};