module.exports = {
    CHANGE_POST: 'CHANGE_POST',
    CHANGE_REPLY: 'CHANGE_REPLY',
    CLEAR_COMMENTS: 'CLEAR_COMMENTS',
    CLEAR_ERROR: 'CLEAR_ERROR',
    CREATE_THREAD: 'CREATE_THREAD',
    DISPLAY_ERROR: 'DISPLAY_ERROR',
    GET_COMMENTS: 'GET_COMMENTS',
    GET_THREADS: 'GET_THREADS',
    SUBMIT_REPLY: 'SUBMIT_REPLY'
};